version: "3"

services:
#   webapp:
#     restart: always
#     build:
#       dockerfile: webapp.Dockerfile
#       context: .
#     ports:
#       - '57210:57210'
# #    links:
# #      - "postgres:postgres"
#     env_file:
#       - phishelizer.env
#       - secrets.env
#     depends_on:
#       - postgres
  app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '8000:8000'
    volumes: 
      - ./:/app
    depends_on:
      - db
    links:
     - "db:postgres"
    environment:
      - DB_ADDRESS=postgres:5432
      - DB_NAME=testdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
        
  db:
    restart: always
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

